config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :articles
  
  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title,  presence: true, length: {minimum: 3, maximum: 50} #presence:true = tornar um campo required
  validates :description,  presence: true,  length: {minimum: 10, maximum: 500}
end

  #No rails console:
  #Visualizar a tabela: Model.all
  #Inserir sem salvar: variavel = Model.new(campo: "valor", campo: "valor").
  #Salvando: variavel.save.
  #Inserindo e salvando de uma vez só: Model.create(campo: "", campo: "").
  #Para mostrar mensagens de erro no Database: model.errors.full_messages

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_filter :redirect_cancel, only: [:create, :update]
  
  def index
    @articles = Article.all #@articles está no plural pois irá pegar TODOS os artigos que estão na base de dados
  end
  
  def new
    @article = Article.new #Instância do objeto Article
  end
  
  def edit
  end
  
  def show
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = "Article was sucessfully created."
      redirect_to article_path(@article)
    else
      render 'new' #Caso não seja criado, renderiza a action new.
    end
  end
  
  def update
    if @article.update(article_params)
      flash[:success] = "Article was sucessfully updated."
      redirect_to article_path(@article)
    else
      render 'edit' #Caso não seja editado, renderiza a action edit.
    end
  end
  
  def destroy
    @article.destroy
    flash[:danger] = "Article was sucessfully deleted."
    redirect_to articles_path
  end
  
  private
    def set_article
      @article = Article.find(params[:id])
    end
  
    def article_params
      params.require(:article).permit(:title, :description) #Parâmetros que serão passados para serem salvos
    end
    
    def redirect_cancel
      redirect_to root_path if params[:cancel]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    
  end
  
  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row"> <!-- Articles CRUD form  -->
  <div class="col-xs-12">
    <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">      
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Write down the article as you want to!" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class:'btn btn-primary' %>
          <%= button_tag t('buttons.cancel'), type: "submit", name: "cancel", value: true, class:'btn btn-danger' %>
        </div>
      </div>
    <% end %> <!-- End loop for the article's form -->
  </div>
</div>

app/views/articles/edit.html.erb
<div class="center">
  <h1>Editing the Article:</h1>
</div>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">List of all articles:</h1>
  
<% @articles.each do |article| %> <!--Loop que percorre a variável @articles -que contém todos os artigos- e exibe em forma de tabela -->
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
        </div>
        <div class="article-actions">
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure to delete this article?"}, class:"btn btn-xs btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/new.html.erb
<div class="center">
  <h1>Creating the Article:</h1>
</div>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center description"><strong>Description</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <div class="article-actions">
  <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary"%>
  <%= link_to "Delete article ", article_path(@article), method: :delete,
                                data: { confirm: "Are you sure you want to delete this article?"},
                                class: "btn btn-xs btn-danger"%>
  <%= link_to "Show all articles", articles_path, class:"btn btn-xs btn-success" %>  
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Developed by <a href="https://bitbucket.org/matheuscunha97">Matheus Cunha</a>
      while <a href="www.udemy.com">Complete Ruby on Rails Developer Course</a> by <a href="www.mashrurhossain.com">Mashrur Hossain</a>.
    </small>
    <nav>
      <ul>
        <li><%= link_to 'About', about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li><##%= link_to "Articles", articles_path, id: "nav_section"%></li>-->
        <li><a href="#" id="nav_links">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" id="nav_links" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Articles<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <!--<form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up", "#", id: "nav_links"%></li>
        <li><%= link_to "Sign In", "#", id: "nav_links"%></li>
        <!--<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<html>
  <head>
  </head>
  
  <body>
    <ul>
      <%= link_to 'Go to Home Section', root_path %>
    </ul>
  </body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Sharing histories of paradises!</h1>
  <%= link_to "Start sharing your history!", "#", class: "btn btn-default btn-lg btn-signup-jumbotron"%>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %> <!-- Validation errors -->
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error")%>
            prohibited this article from being created:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %> <!-- End of validation errors -->